// flow-typed signature: 5fd87cd36553d1fb7ac1a0f26d05245f
// flow-typed version: <<STUB>>/camo_v0.12.3/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'camo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'camo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'camo/lib/base-document' {
  declare module.exports: any;
}

declare module 'camo/lib/clients/client' {
  declare module.exports: any;
}

declare module 'camo/lib/clients/index' {
  declare module.exports: any;
}

declare module 'camo/lib/clients/mongoclient' {
  declare module.exports: any;
}

declare module 'camo/lib/clients/nedbclient' {
  declare module.exports: any;
}

declare module 'camo/lib/db' {
  declare module.exports: any;
}

declare module 'camo/lib/document' {
  declare module.exports: any;
}

declare module 'camo/lib/embedded-document' {
  declare module.exports: any;
}

declare module 'camo/lib/errors' {
  declare module.exports: any;
}

declare module 'camo/lib/util' {
  declare module.exports: any;
}

declare module 'camo/lib/validate' {
  declare module.exports: any;
}

declare module 'camo/test/client.test' {
  declare module.exports: any;
}

declare module 'camo/test/cyclic.test' {
  declare module.exports: any;
}

declare module 'camo/test/cyclic/bar' {
  declare module.exports: any;
}

declare module 'camo/test/cyclic/foo' {
  declare module.exports: any;
}

declare module 'camo/test/data' {
  declare module.exports: any;
}

declare module 'camo/test/document.test' {
  declare module.exports: any;
}

declare module 'camo/test/embedded.test' {
  declare module.exports: any;
}

declare module 'camo/test/issues.test' {
  declare module.exports: any;
}

declare module 'camo/test/mongoclient.test' {
  declare module.exports: any;
}

declare module 'camo/test/nedbclient.test' {
  declare module.exports: any;
}

declare module 'camo/test/util' {
  declare module.exports: any;
}

declare module 'camo/test/util.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'camo/index' {
  declare module.exports: $Exports<'camo'>;
}
declare module 'camo/index.js' {
  declare module.exports: $Exports<'camo'>;
}
declare module 'camo/lib/base-document.js' {
  declare module.exports: $Exports<'camo/lib/base-document'>;
}
declare module 'camo/lib/clients/client.js' {
  declare module.exports: $Exports<'camo/lib/clients/client'>;
}
declare module 'camo/lib/clients/index.js' {
  declare module.exports: $Exports<'camo/lib/clients/index'>;
}
declare module 'camo/lib/clients/mongoclient.js' {
  declare module.exports: $Exports<'camo/lib/clients/mongoclient'>;
}
declare module 'camo/lib/clients/nedbclient.js' {
  declare module.exports: $Exports<'camo/lib/clients/nedbclient'>;
}
declare module 'camo/lib/db.js' {
  declare module.exports: $Exports<'camo/lib/db'>;
}
declare module 'camo/lib/document.js' {
  declare module.exports: $Exports<'camo/lib/document'>;
}
declare module 'camo/lib/embedded-document.js' {
  declare module.exports: $Exports<'camo/lib/embedded-document'>;
}
declare module 'camo/lib/errors.js' {
  declare module.exports: $Exports<'camo/lib/errors'>;
}
declare module 'camo/lib/util.js' {
  declare module.exports: $Exports<'camo/lib/util'>;
}
declare module 'camo/lib/validate.js' {
  declare module.exports: $Exports<'camo/lib/validate'>;
}
declare module 'camo/test/client.test.js' {
  declare module.exports: $Exports<'camo/test/client.test'>;
}
declare module 'camo/test/cyclic.test.js' {
  declare module.exports: $Exports<'camo/test/cyclic.test'>;
}
declare module 'camo/test/cyclic/bar.js' {
  declare module.exports: $Exports<'camo/test/cyclic/bar'>;
}
declare module 'camo/test/cyclic/foo.js' {
  declare module.exports: $Exports<'camo/test/cyclic/foo'>;
}
declare module 'camo/test/data.js' {
  declare module.exports: $Exports<'camo/test/data'>;
}
declare module 'camo/test/document.test.js' {
  declare module.exports: $Exports<'camo/test/document.test'>;
}
declare module 'camo/test/embedded.test.js' {
  declare module.exports: $Exports<'camo/test/embedded.test'>;
}
declare module 'camo/test/issues.test.js' {
  declare module.exports: $Exports<'camo/test/issues.test'>;
}
declare module 'camo/test/mongoclient.test.js' {
  declare module.exports: $Exports<'camo/test/mongoclient.test'>;
}
declare module 'camo/test/nedbclient.test.js' {
  declare module.exports: $Exports<'camo/test/nedbclient.test'>;
}
declare module 'camo/test/util.js' {
  declare module.exports: $Exports<'camo/test/util'>;
}
declare module 'camo/test/util.test.js' {
  declare module.exports: $Exports<'camo/test/util.test'>;
}
