// flow-typed signature: 245a8a7837e2470953928282e41cfd09
// flow-typed version: <<STUB>>/electron-is_v3.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-is'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-is' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-is/is' {
  declare module.exports: any;
}

declare module 'electron-is/test/assertions' {
  declare module.exports: any;
}

declare module 'electron-is/test/headless-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-is/is.js' {
  declare module.exports: $Exports<'electron-is/is'>;
}
declare module 'electron-is/test/assertions.js' {
  declare module.exports: $Exports<'electron-is/test/assertions'>;
}
declare module 'electron-is/test/headless-test.js' {
  declare module.exports: $Exports<'electron-is/test/headless-test'>;
}
